# Generated by Django 2.1.7 on 2019-03-13 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='descricao',
            field=models.TextField(default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cadastro',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
